### PR TITLE
docs: fix install instruction in README

### PR DESCRIPTION
**Pull request by kontrollanten**
preact-async-route should be installed as a production dependency

### CODE REVIEW

**Comment by prateekbh** [comment]
Why again? I thought you can just add this as dev dependency and everything gets transpiled to js.

**Comment by kontrollanten** [comment]
I may be wrong here, but as I understand PreactAsyncRoute is imported and running in the application and therefore it should be used as a production dependency. Even though it (mostly) will work good to have it as a dev dependency. It's just details, but setting it as devDep is the semantic correct.

**Comment by prateekbh** [comment]
i guess production deps are something which you need to download at production time, like may be your http-server, you runtime compression lib. this is something you download at dev time traspile in a bundle and deploy, you dont need it at production servers or runtime

**Comment by kontrollanten** [comment]
I'm not sure I'm with you here. As I see it, the main purpose of separating dev/prod deps is when developing npm packages. Package C imports package A as dev and B as prod dep. When some other project imports package C, it will just download package B. Then it is up to this other project whether they want to transpile it or not.

In this case. If I create a npm package that will use `preact-async-route`. The consumers of my package also need to download `preact-async-route`, otherwise the import statements will failed due to not finding `preact-async-route`. Therefore it should be a prod package.

That's my view of how it works. But anyway, this was just a detail. I guess the users of preact-async-route can choose by themselves how they want to declare the package. :-)

**Comment by prateekbh** [comment]
Ah I see it, yes you are correct. And this does leave me confused, I wrote the `README` from the POV of an end user app, what you wrote it is POV of npm dep

**Comment by prateekbh** [comment]
closing in favor of basic usage, being a package dev yourself, you might have better understanding of choosing the dependency place than a normal user.

**Pull request closed without merging**
