### PR TITLE
fix(props-typescript): adding type check for props to <AsyncRoute />

### PR DESCRIPTION
**Pull request by minaseem**

### CODE REVIEW

**Comment by prateekbh** [comment]
Can you post a small description of whats happening here? Would be super helpful for TS noobs like me

**Comment by minaseem** [comment]
`[key: string]: any` says that all the other `props` can be of `any` type. This way we can have as many props passed to `<AsyncRoute/>` 

PS: I have just started studying TS. Let me know if you have better suggestion

**Comment by prateekbh** [comment]
small request to bump the patch version

**Comment by minaseem** [comment]
updated patch version

**Pull request merged**
