### PR TITLE
Updated some things in the package.json and example in readme

### PR DESCRIPTION
**Pull request by mjanssen**
- Using `import()` instead of `System.import()` https://github.com/webpack/webpack/pull/4269.
- Use the `index.min.js` file when importing, rather than the unminified `index.js`.
- Changed `peerdependencies` to `peerDependencies` in package.json, so bundle size checkers can check the size.
- Added gzip-size badge to Readme

### CODE REVIEW

**Comment by mjanssen** [comment]
What is even breaking it 🤔☹️

**Comment by prateekbh** [comment]
just travis's problem

**Comment by prateekbh** [comment]
@mjanssen I wonder if this would need a change in babel-transform

**Comment by mjanssen** [comment]
Hmm, why do you think it requires a change? I think the lib will still build as its supposed to. I can  check if the building process can be updated tho 🤔

**Comment by prateekbh** [comment]
I guess babel had a specific plugin for this `import`, for the browsers that does not have this. Or is this  handled by webpack?

**Comment by mjanssen** [comment]
It's handled by Webpack 😃.
I mentioned the PR on that 'issue' in the initial comment (webpack/webpack#4269)

**Pull request merged**
