### PR TITLE
Import JSX from preact.

### PR DESCRIPTION
**Pull request by pmkroeker**
For [preact@next](https://github.com/developit/preact/releases/tag/10.0.0-beta.0) (beta), the `JSX` namespace has been moved, under the `preact` namespace. For some reason this change causes an error in a test case, but code used by it compiles correctly.

### CODE REVIEW

**Comment by prateekbh** [comment]
i'll just wait for it to be stable before this

**Comment by pmkroeker** [comment]
Could you potentially release an `@next` version with this change? Would help the people migrating between the versions.

**Comment by prateekbh** [comment]
woops failing test!!!!

**Comment by pmkroeker** [comment]
Hmm, looking into it. Seems as though if `getComponent` does not return a promise it doesn't render properly.

**Comment by pmkroeker** [comment]
Bumping the typescript version fixed one or the TS issues. The other one where `preact-router` throws in a (known issue)[https://github.com/developit/preact-router/pull/308]. And will be gone once it undergoes the proper namespacing changes as well. As for why one of the default tests fails, must be a change in the implementation by `preact-router`. I changed none of the code in the `js` files. So something else must have changed something to make this test fail.

**Comment by pmkroeker** [comment]
Seems changing the lifecycle method `componentWillMount` to `componentDidMount` fixes the failing test.

**Comment by pmkroeker** [comment]
JSX has now been moved into the preact namespace in the latest version of the 8.x line.

**Pull request closed without merging**
